image: ruby:2.3

pages:
  stage: deploy
  script:
  - export LANG=en_US.UTF-8
  - gem install jekyll
  - jekyll build -d public
  - echo "prod" > public/env
  artifacts:
    paths:
    - public
  only:
  - master
